- name: Include HTTPd
  include: ../Shared/HTTPd/main.yaml

- name: Add NextCloud Config to HTTPd
  vars:
    ServerName: "{{ host_name }}.{{ host_public_domain }}"
  ansible.builtin.template:
    src: ./templates/nextcloud_httpd_config.j2
    dest: /etc/httpd/conf.d/nextcloud.conf
