- name: Install EPEL
  ansible.builtin.package:
    name: epel-release
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Fedora'

- name: Install Base Packages
  ansible.builtin.package:
    name:
      - sudo
      - firewalld
      - python3-devel
      - git
      - zsh
