- name: Ping HASS
  ansible.builtin.ping:

- name: Include Install
  include: install.yaml

- name: Include Firewalld
  include: firewalld.yaml

# Why does this take so long?
- name: Include SELinux
  include: selinux.yaml

- name: Include Mariadb
  include: ../Shared/MariaDB/main.yaml

- name: Setup HomeAssistant
  include: hass_setup.yaml

- name: Add Caddy Config for HASS
  delegate_to: "{{ groups['Caddy'][0] }}"
  ansible.builtin.template:
    src: ./templates/caddy_config.j2
    dest: /etc/caddy/sites-enabled/hass_config
  notify:
    - Restart Caddy
